language: r

matrix:
  include:
    - r: oldrel
      os: linux
      dist: trusty
      sudo: false
    - r: release
      os: linux
      dist: trusty
      sudo: false
      env: 
        - TEST_GOLUB=TRUE
    - r: devel
      os: linux
      sudo: false
      dist: trusty
    - r: release
      os: osx
      env:
        - TEST_GOLUB=TRUE

env:
  - MAKE="make -j4"
