language: r
sudo: true

r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

matrix:
  exclude:
  - r: oldrel
    os: osx
  - r: devel
    os: osx

addons:
  apt:
    packages:
      - nvidia-cuda-toolkit
