language: r

matrix:
  include:
    - r: oldrel
      os: linux
      sudo: false
    - r: release
      os: linux
      sudo: false
    - r: devel
      os: linux
      sudo: false
    - r: release
      os: osx

