# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.test.dgemm <- function(a, b, retval) {
    invisible(.Call(`_supc_test_dgemm`, a, b, retval))
}

.supc1.cpp.internal <- function(x, tau, RT, tolerance, dist, verbose) {
    .Call(`_supc_supc1_cpp`, x, tau, RT, tolerance, dist, verbose)
}

.supc1.cpp2.internal <- function(x, tau, RT, tolerance, verbose) {
    .Call(`_supc_supc1_cpp2`, x, tau, RT, tolerance, verbose)
}

.supc.random.cpp.internal <- function(x, tau, RT, k, groups, tolerance, verbose) {
    .Call(`_supc_supc_random_cpp`, x, tau, RT, k, groups, tolerance, verbose)
}

.test.dist <- function(x) {
    .Call(`_supc_test_dist`, x)
}

