# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.get_sorted_index <- function(input) {
    .Call(`_supc_get_sorted_index`, input)
}

.get_inverted_index_for_sorted_index <- function(input) {
    .Call(`_supc_get_inverted_index_for_sorted_index`, input)
}

.clusterize <- function(X, threshold, reference_j = -1L) {
    .Call(`_supc_clusterize`, X, threshold, reference_j)
}

.set_num_threads <- function(x) {
    invisible(.Call(`_supc_set_num_threads`, x))
}

.test.dgemm <- function(a, b, retval) {
    invisible(.Call(`_supc_test_dgemm`, a, b, retval))
}

.supc1.cpp.internal <- function(x, tau, RT, tolerance, dist, verbose) {
    .Call(`_supc_supc1_cpp`, x, tau, RT, tolerance, dist, verbose)
}

.supc1.cpp2.internal <- function(x, tau, RT, tolerance, verbose) {
    .Call(`_supc_supc1_cpp2`, x, tau, RT, tolerance, verbose)
}

.supc.random.cpp.internal <- function(x, tau, RT, k, groups, tolerance, verbose) {
    .Call(`_supc_supc_random_cpp`, x, tau, RT, k, groups, tolerance, verbose)
}

.test.runtime.nthread <- function() {
    .Call(`_supc_test_runtime_nthread`)
}

.test.dist <- function(x) {
    .Call(`_supc_test_dist`, x)
}

