# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.clusterize <- function(dist, tolerance) {
    .Call('supc_clusterize', PACKAGE = 'supc', dist, tolerance)
}

.test.dgemm <- function(a, b, retval) {
    invisible(.Call('supc_test_dgemm', PACKAGE = 'supc', a, b, retval))
}

.supc1.cpp.internal <- function(x, tau, RT, tolerance, dist, verbose) {
    .Call('supc_supc1_cpp', PACKAGE = 'supc', x, tau, RT, tolerance, dist, verbose)
}

